### ISSUE TITLE
Ruru example error 

### ISSUE THREAD

**Issue by zacksiri** [steveklabnik/rust_example#14]
Hey

I managed to get the ruru example to compile however i am getting this error when I try to run the ruby script.

``` shell
example.rb:1:in `require_relative': cannot load such file -- /Users/zacksiri/Repositories/rust_example/ruru/target/release/librurulol (LoadError)
```

here is the `target/release` directory after running `cargo build --release`

``` shell
build            deps             examples         librurulol.dylib native
```

**Comment by steveklabnik** [comment]
I committed the version for linux, but you're on OSX. You need to modify the source to say `librurulol.dylib` rsather than `librurulol.so`.

**Comment by zacksiri** [comment]
Where do I change that? i don't see any reference to either.

Sorry i am quite a noob to this ;)

**Comment by steveklabnik** [comment]
Sorry, It's `.a`, not `.so`: https://github.com/steveklabnik/rust_example/blob/master/Makefile#L3

**Comment by steveklabnik** [comment]
(and it's all good, it's been a while since I"ve played with this repo, as you can see, I'm fuzzy on the exact details myself! the newest rust also just came with a `cdylib` type that this should probably be using now...)

**Comment by zacksiri** [comment]
@steveklabnik thx for replying! I managed to get it to work here 

https://github.com/codemy/ruru_example 

I am going to work on writing more rust code now, as I am working on an application, where I need to be able to control memory usage, and relying on Ruby's GC is just not enough anymore.

Been reading through the rust documentation I know you had a major hand in that so thank you for your efforts!

**Comment by steveklabnik** [comment]
Awesome! Feel free to post any questions on our forums or drop by IRC if you need help. Good luck! :)
