### ISSUE TITLE
What about FFI?

### ISSUE THREAD

**Issue by nathanaeljones** [steveklabnik/rust_example#9]
Is there any reason that we can't (or shouldn't?) use the FFI gem to call into a Rust dylib directly? I'm considering building a very large Rust+C library (low-latency image asset processing) and exposing it to Ruby.

**Comment by steveklabnik** [comment]
FFI is totally doable in this case: http://doc.rust-lang.org/stable/book/rust-inside-other-languages.html#ruby

The purpose of this repository is to show another way.
